### ISSUE TITLE
remove skidded client

### ISSUE THREAD

**Issue by xkeksi** [MarkGG8181/WonderlandLibrary#1]
this client is a very pasted mess.
please remove this from github.
Koks v3/v4 GCD (mouse sensitivity) fix
azura setmotion method
liquidbounce bruteforce rotations
wrong besthitvector
80x strafe methods

**Comment by MarkGG8181** [comment]
> this client is a very pasted mess. please remove this from github. Koks v3/v4 GCD (mouse sensitivity) fix liquidbounce bruteforce rotations wrong besthitvector 80x strafe methods

This is a client archive. How have you mistaken a client archive for an individual client?

**Comment by MarkGG8181** [comment]
> > > this client is a very pasted mess. please remove this from github. Koks v3/v4 GCD (mouse sensitivity) fix liquidbounce bruteforce rotations wrong besthitvector 80x strafe methods
> > 
> > 
> > This is a client archive. How have you mistaken a client archive for an individual client?
> 
> i am trolling lmao atani is the biggest paste/shit client ive seen lmao

okay, but didn’t ask?

**Comment by xkeksi** [comment]
mad

**Comment by MarkGG8181** [comment]
> mad

are you actually braindead? this is a fucking client source/jar archive not a repo for a specific client

**Comment by xkeksi** [comment]
> > mad
> 
> are you actually braindead? this is a fucking client source/jar archive not a repo for a specific client

mad? 😩 
🤪 👏 bro still thinks im not trolling 🤒 😞 how obv should i 🤪 make it 🚬

**Comment by MarkGG8181** [comment]
> > > mad
> > 
> > 
> > are you actually braindead? this is a fucking client source/jar archive not a repo for a specific client
> 
> mad? 😩 🤪 👏 bro still thinks im not trolling 🤒 😞 how obv should i 🤪 make it 🚬

actually kys
